secret:
  secret_key_base: "rake secret"

database:
  pool: 2
  host: localhost
  port: 3306
  username: root
  password:
  database:
    development: sample_app_rails_4_development
    test: sample_app_rails_4_test
    production: sample_app_rails_4_production
